// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	models "github.com/JasonKhew96/margaretbot/models"
	"github.com/aarondl/opt/null"
)

type Factory struct {
	baseCacheMods        CacheModSlice
	baseSubscriptionMods SubscriptionModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewCache(mods ...CacheMod) *CacheTemplate {
	return f.NewCacheWithContext(context.Background(), mods...)
}

func (f *Factory) NewCacheWithContext(ctx context.Context, mods ...CacheMod) *CacheTemplate {
	o := &CacheTemplate{f: f}

	if f != nil {
		f.baseCacheMods.Apply(ctx, o)
	}

	CacheModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingCache(m *models.Cache) *CacheTemplate {
	o := &CacheTemplate{f: f, alreadyPersisted: true}

	o.VideoID = func() string { return m.VideoID }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }
	o.IsPublished = func() bool { return m.IsPublished }
	o.IsScheduled = func() bool { return m.IsScheduled }

	return o
}

func (f *Factory) NewSubscription(mods ...SubscriptionMod) *SubscriptionTemplate {
	return f.NewSubscriptionWithContext(context.Background(), mods...)
}

func (f *Factory) NewSubscriptionWithContext(ctx context.Context, mods ...SubscriptionMod) *SubscriptionTemplate {
	o := &SubscriptionTemplate{f: f}

	if f != nil {
		f.baseSubscriptionMods.Apply(ctx, o)
	}

	SubscriptionModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingSubscription(m *models.Subscription) *SubscriptionTemplate {
	o := &SubscriptionTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.ChannelID = func() string { return m.ChannelID }
	o.Regex = func() null.Val[string] { return m.Regex }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }
	o.RegexBan = func() null.Val[string] { return m.RegexBan }
	o.ChannelTitle = func() null.Val[string] { return m.ChannelTitle }
	o.ExpiredAt = func() null.Val[time.Time] { return m.ExpiredAt }
	o.ThreadID = func() int64 { return m.ThreadID }

	return o
}

func (f *Factory) ClearBaseCacheMods() {
	f.baseCacheMods = nil
}

func (f *Factory) AddBaseCacheMod(mods ...CacheMod) {
	f.baseCacheMods = append(f.baseCacheMods, mods...)
}

func (f *Factory) ClearBaseSubscriptionMods() {
	f.baseSubscriptionMods = nil
}

func (f *Factory) AddBaseSubscriptionMod(mods ...SubscriptionMod) {
	f.baseSubscriptionMods = append(f.baseSubscriptionMods, mods...)
}
