// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	// Relationship Contexts for cache
	cacheWithParentsCascadingCtx = newContextual[bool]("cacheWithParentsCascading")

	// Relationship Contexts for forward
	forwardWithParentsCascadingCtx = newContextual[bool]("forwardWithParentsCascading")

	// Relationship Contexts for forward_no
	forwardNoWithParentsCascadingCtx = newContextual[bool]("forwardNoWithParentsCascading")

	// Relationship Contexts for subscription
	subscriptionWithParentsCascadingCtx = newContextual[bool]("subscriptionWithParentsCascading")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
