// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	models "github.com/JasonKhew96/margaretbot/models"
	"github.com/aarondl/opt/null"
)

type Factory struct {
	baseCacheMods        CacheModSlice
	baseForwardMods      ForwardModSlice
	baseForwardNoMods    ForwardNoModSlice
	baseSubscriptionMods SubscriptionModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewCache(mods ...CacheMod) *CacheTemplate {
	return f.NewCacheWithContext(context.Background(), mods...)
}

func (f *Factory) NewCacheWithContext(ctx context.Context, mods ...CacheMod) *CacheTemplate {
	o := &CacheTemplate{f: f}

	if f != nil {
		f.baseCacheMods.Apply(ctx, o)
	}

	CacheModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingCache(m *models.Cache) *CacheTemplate {
	o := &CacheTemplate{f: f, alreadyPersisted: true}

	o.VideoID = func() string { return m.VideoID }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }
	o.IsPublished = func() bool { return m.IsPublished }
	o.IsScheduled = func() bool { return m.IsScheduled }

	return o
}

func (f *Factory) NewForward(mods ...ForwardMod) *ForwardTemplate {
	return f.NewForwardWithContext(context.Background(), mods...)
}

func (f *Factory) NewForwardWithContext(ctx context.Context, mods ...ForwardMod) *ForwardTemplate {
	o := &ForwardTemplate{f: f}

	if f != nil {
		f.baseForwardMods.Apply(ctx, o)
	}

	ForwardModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingForward(m *models.Forward) *ForwardTemplate {
	o := &ForwardTemplate{f: f, alreadyPersisted: true}

	o.ChatID = func() int64 { return m.ChatID }
	o.Regex = func() null.Val[string] { return m.Regex }
	o.RegexBan = func() null.Val[string] { return m.RegexBan }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	return o
}

func (f *Factory) NewForwardNo(mods ...ForwardNoMod) *ForwardNoTemplate {
	return f.NewForwardNoWithContext(context.Background(), mods...)
}

func (f *Factory) NewForwardNoWithContext(ctx context.Context, mods ...ForwardNoMod) *ForwardNoTemplate {
	o := &ForwardNoTemplate{f: f}

	if f != nil {
		f.baseForwardNoMods.Apply(ctx, o)
	}

	ForwardNoModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingForwardNo(m *models.ForwardNo) *ForwardNoTemplate {
	o := &ForwardNoTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.ChatID = func() int64 { return m.ChatID }
	o.ChannelID = func() string { return m.ChannelID }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	return o
}

func (f *Factory) NewSubscription(mods ...SubscriptionMod) *SubscriptionTemplate {
	return f.NewSubscriptionWithContext(context.Background(), mods...)
}

func (f *Factory) NewSubscriptionWithContext(ctx context.Context, mods ...SubscriptionMod) *SubscriptionTemplate {
	o := &SubscriptionTemplate{f: f}

	if f != nil {
		f.baseSubscriptionMods.Apply(ctx, o)
	}

	SubscriptionModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingSubscription(m *models.Subscription) *SubscriptionTemplate {
	o := &SubscriptionTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.ChannelID = func() string { return m.ChannelID }
	o.Regex = func() null.Val[string] { return m.Regex }
	o.RegexBan = func() null.Val[string] { return m.RegexBan }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }
	o.ChannelTitle = func() null.Val[string] { return m.ChannelTitle }
	o.ExpiredAt = func() null.Val[time.Time] { return m.ExpiredAt }
	o.ThreadID = func() int64 { return m.ThreadID }

	return o
}

func (f *Factory) ClearBaseCacheMods() {
	f.baseCacheMods = nil
}

func (f *Factory) AddBaseCacheMod(mods ...CacheMod) {
	f.baseCacheMods = append(f.baseCacheMods, mods...)
}

func (f *Factory) ClearBaseForwardMods() {
	f.baseForwardMods = nil
}

func (f *Factory) AddBaseForwardMod(mods ...ForwardMod) {
	f.baseForwardMods = append(f.baseForwardMods, mods...)
}

func (f *Factory) ClearBaseForwardNoMods() {
	f.baseForwardNoMods = nil
}

func (f *Factory) AddBaseForwardNoMod(mods ...ForwardNoMod) {
	f.baseForwardNoMods = append(f.baseForwardNoMods, mods...)
}

func (f *Factory) ClearBaseSubscriptionMods() {
	f.baseSubscriptionMods = nil
}

func (f *Factory) AddBaseSubscriptionMod(mods ...SubscriptionMod) {
	f.baseSubscriptionMods = append(f.baseSubscriptionMods, mods...)
}
