// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/JasonKhew96/margaretbot/models"
	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type CacheMod interface {
	Apply(context.Context, *CacheTemplate)
}

type CacheModFunc func(context.Context, *CacheTemplate)

func (f CacheModFunc) Apply(ctx context.Context, n *CacheTemplate) {
	f(ctx, n)
}

type CacheModSlice []CacheMod

func (mods CacheModSlice) Apply(ctx context.Context, n *CacheTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// CacheTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type CacheTemplate struct {
	VideoID     func() string
	CreatedAt   func() time.Time
	UpdatedAt   func() time.Time
	IsPublished func() bool
	IsScheduled func() bool

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the CacheTemplate
func (o *CacheTemplate) Apply(ctx context.Context, mods ...CacheMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Cache
// according to the relationships in the template. Nothing is inserted into the db
func (t CacheTemplate) setModelRels(o *models.Cache) {}

// BuildSetter returns an *models.CacheSetter
// this does nothing with the relationship templates
func (o CacheTemplate) BuildSetter() *models.CacheSetter {
	m := &models.CacheSetter{}

	if o.VideoID != nil {
		val := o.VideoID()
		m.VideoID = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}
	if o.IsPublished != nil {
		val := o.IsPublished()
		m.IsPublished = omit.From(val)
	}
	if o.IsScheduled != nil {
		val := o.IsScheduled()
		m.IsScheduled = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.CacheSetter
// this does nothing with the relationship templates
func (o CacheTemplate) BuildManySetter(number int) []*models.CacheSetter {
	m := make([]*models.CacheSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Cache
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CacheTemplate.Create
func (o CacheTemplate) Build() *models.Cache {
	m := &models.Cache{}

	if o.VideoID != nil {
		m.VideoID = o.VideoID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}
	if o.IsPublished != nil {
		m.IsPublished = o.IsPublished()
	}
	if o.IsScheduled != nil {
		m.IsScheduled = o.IsScheduled()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.CacheSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CacheTemplate.CreateMany
func (o CacheTemplate) BuildMany(number int) models.CacheSlice {
	m := make(models.CacheSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableCache(m *models.CacheSetter) {
	if !(m.VideoID.IsValue()) {
		val := random_string(nil)
		m.VideoID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Cache
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *CacheTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Cache) error {
	var err error

	return err
}

// Create builds a cache and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *CacheTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Cache, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableCache(opt)

	m, err := models.Caches.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a cache and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *CacheTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Cache {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a cache and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *CacheTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Cache {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple caches and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o CacheTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.CacheSlice, error) {
	var err error
	m := make(models.CacheSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple caches and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o CacheTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.CacheSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple caches and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o CacheTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.CacheSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Cache has methods that act as mods for the CacheTemplate
var CacheMods cacheMods

type cacheMods struct{}

func (m cacheMods) RandomizeAllColumns(f *faker.Faker) CacheMod {
	return CacheModSlice{
		CacheMods.RandomVideoID(f),
		CacheMods.RandomCreatedAt(f),
		CacheMods.RandomUpdatedAt(f),
		CacheMods.RandomIsPublished(f),
		CacheMods.RandomIsScheduled(f),
	}
}

// Set the model columns to this value
func (m cacheMods) VideoID(val string) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.VideoID = func() string { return val }
	})
}

// Set the Column from the function
func (m cacheMods) VideoIDFunc(f func() string) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.VideoID = f
	})
}

// Clear any values for the column
func (m cacheMods) UnsetVideoID() CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.VideoID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cacheMods) RandomVideoID(f *faker.Faker) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.VideoID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m cacheMods) CreatedAt(val time.Time) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m cacheMods) CreatedAtFunc(f func() time.Time) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m cacheMods) UnsetCreatedAt() CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cacheMods) RandomCreatedAt(f *faker.Faker) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m cacheMods) UpdatedAt(val time.Time) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m cacheMods) UpdatedAtFunc(f func() time.Time) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m cacheMods) UnsetUpdatedAt() CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cacheMods) RandomUpdatedAt(f *faker.Faker) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m cacheMods) IsPublished(val bool) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.IsPublished = func() bool { return val }
	})
}

// Set the Column from the function
func (m cacheMods) IsPublishedFunc(f func() bool) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.IsPublished = f
	})
}

// Clear any values for the column
func (m cacheMods) UnsetIsPublished() CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.IsPublished = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cacheMods) RandomIsPublished(f *faker.Faker) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.IsPublished = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m cacheMods) IsScheduled(val bool) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.IsScheduled = func() bool { return val }
	})
}

// Set the Column from the function
func (m cacheMods) IsScheduledFunc(f func() bool) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.IsScheduled = f
	})
}

// Clear any values for the column
func (m cacheMods) UnsetIsScheduled() CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.IsScheduled = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cacheMods) RandomIsScheduled(f *faker.Faker) CacheMod {
	return CacheModFunc(func(_ context.Context, o *CacheTemplate) {
		o.IsScheduled = func() bool {
			return random_bool(f)
		}
	})
}

func (m cacheMods) WithParentsCascading() CacheMod {
	return CacheModFunc(func(ctx context.Context, o *CacheTemplate) {
		if isDone, _ := cacheWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = cacheWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
