// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/JasonKhew96/margaretbot/models"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type ForwardMod interface {
	Apply(context.Context, *ForwardTemplate)
}

type ForwardModFunc func(context.Context, *ForwardTemplate)

func (f ForwardModFunc) Apply(ctx context.Context, n *ForwardTemplate) {
	f(ctx, n)
}

type ForwardModSlice []ForwardMod

func (mods ForwardModSlice) Apply(ctx context.Context, n *ForwardTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ForwardTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ForwardTemplate struct {
	ChatID    func() int64
	Regex     func() null.Val[string]
	RegexBan  func() null.Val[string]
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the ForwardTemplate
func (o *ForwardTemplate) Apply(ctx context.Context, mods ...ForwardMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Forward
// according to the relationships in the template. Nothing is inserted into the db
func (t ForwardTemplate) setModelRels(o *models.Forward) {}

// BuildSetter returns an *models.ForwardSetter
// this does nothing with the relationship templates
func (o ForwardTemplate) BuildSetter() *models.ForwardSetter {
	m := &models.ForwardSetter{}

	if o.ChatID != nil {
		val := o.ChatID()
		m.ChatID = omit.From(val)
	}
	if o.Regex != nil {
		val := o.Regex()
		m.Regex = omitnull.FromNull(val)
	}
	if o.RegexBan != nil {
		val := o.RegexBan()
		m.RegexBan = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ForwardSetter
// this does nothing with the relationship templates
func (o ForwardTemplate) BuildManySetter(number int) []*models.ForwardSetter {
	m := make([]*models.ForwardSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Forward
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ForwardTemplate.Create
func (o ForwardTemplate) Build() *models.Forward {
	m := &models.Forward{}

	if o.ChatID != nil {
		m.ChatID = o.ChatID()
	}
	if o.Regex != nil {
		m.Regex = o.Regex()
	}
	if o.RegexBan != nil {
		m.RegexBan = o.RegexBan()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ForwardSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ForwardTemplate.CreateMany
func (o ForwardTemplate) BuildMany(number int) models.ForwardSlice {
	m := make(models.ForwardSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableForward(m *models.ForwardSetter) {
}

// insertOptRels creates and inserts any optional the relationships on *models.Forward
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ForwardTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Forward) error {
	var err error

	return err
}

// Create builds a forward and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ForwardTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Forward, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableForward(opt)

	m, err := models.Forwards.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a forward and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ForwardTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Forward {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a forward and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ForwardTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Forward {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple forwards and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ForwardTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ForwardSlice, error) {
	var err error
	m := make(models.ForwardSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple forwards and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ForwardTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ForwardSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple forwards and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ForwardTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ForwardSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Forward has methods that act as mods for the ForwardTemplate
var ForwardMods forwardMods

type forwardMods struct{}

func (m forwardMods) RandomizeAllColumns(f *faker.Faker) ForwardMod {
	return ForwardModSlice{
		ForwardMods.RandomChatID(f),
		ForwardMods.RandomRegex(f),
		ForwardMods.RandomRegexBan(f),
		ForwardMods.RandomCreatedAt(f),
		ForwardMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m forwardMods) ChatID(val int64) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.ChatID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m forwardMods) ChatIDFunc(f func() int64) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.ChatID = f
	})
}

// Clear any values for the column
func (m forwardMods) UnsetChatID() ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.ChatID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m forwardMods) RandomChatID(f *faker.Faker) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.ChatID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m forwardMods) Regex(val null.Val[string]) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.Regex = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m forwardMods) RegexFunc(f func() null.Val[string]) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.Regex = f
	})
}

// Clear any values for the column
func (m forwardMods) UnsetRegex() ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.Regex = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m forwardMods) RandomRegex(f *faker.Faker) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.Regex = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m forwardMods) RandomRegexNotNull(f *faker.Faker) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.Regex = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m forwardMods) RegexBan(val null.Val[string]) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.RegexBan = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m forwardMods) RegexBanFunc(f func() null.Val[string]) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.RegexBan = f
	})
}

// Clear any values for the column
func (m forwardMods) UnsetRegexBan() ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.RegexBan = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m forwardMods) RandomRegexBan(f *faker.Faker) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.RegexBan = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m forwardMods) RandomRegexBanNotNull(f *faker.Faker) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.RegexBan = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m forwardMods) CreatedAt(val time.Time) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m forwardMods) CreatedAtFunc(f func() time.Time) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m forwardMods) UnsetCreatedAt() ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m forwardMods) RandomCreatedAt(f *faker.Faker) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m forwardMods) UpdatedAt(val time.Time) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m forwardMods) UpdatedAtFunc(f func() time.Time) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m forwardMods) UnsetUpdatedAt() ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m forwardMods) RandomUpdatedAt(f *faker.Faker) ForwardMod {
	return ForwardModFunc(func(_ context.Context, o *ForwardTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m forwardMods) WithParentsCascading() ForwardMod {
	return ForwardModFunc(func(ctx context.Context, o *ForwardTemplate) {
		if isDone, _ := forwardWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = forwardWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
