// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/JasonKhew96/margaretbot/models"
	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type ForwardNoMod interface {
	Apply(context.Context, *ForwardNoTemplate)
}

type ForwardNoModFunc func(context.Context, *ForwardNoTemplate)

func (f ForwardNoModFunc) Apply(ctx context.Context, n *ForwardNoTemplate) {
	f(ctx, n)
}

type ForwardNoModSlice []ForwardNoMod

func (mods ForwardNoModSlice) Apply(ctx context.Context, n *ForwardNoTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ForwardNoTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ForwardNoTemplate struct {
	ID        func() int64
	ChatID    func() int64
	ChannelID func() string
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the ForwardNoTemplate
func (o *ForwardNoTemplate) Apply(ctx context.Context, mods ...ForwardNoMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.ForwardNo
// according to the relationships in the template. Nothing is inserted into the db
func (t ForwardNoTemplate) setModelRels(o *models.ForwardNo) {}

// BuildSetter returns an *models.ForwardNoSetter
// this does nothing with the relationship templates
func (o ForwardNoTemplate) BuildSetter() *models.ForwardNoSetter {
	m := &models.ForwardNoSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.ChatID != nil {
		val := o.ChatID()
		m.ChatID = omit.From(val)
	}
	if o.ChannelID != nil {
		val := o.ChannelID()
		m.ChannelID = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ForwardNoSetter
// this does nothing with the relationship templates
func (o ForwardNoTemplate) BuildManySetter(number int) []*models.ForwardNoSetter {
	m := make([]*models.ForwardNoSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.ForwardNo
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ForwardNoTemplate.Create
func (o ForwardNoTemplate) Build() *models.ForwardNo {
	m := &models.ForwardNo{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.ChatID != nil {
		m.ChatID = o.ChatID()
	}
	if o.ChannelID != nil {
		m.ChannelID = o.ChannelID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ForwardNoSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ForwardNoTemplate.CreateMany
func (o ForwardNoTemplate) BuildMany(number int) models.ForwardNoSlice {
	m := make(models.ForwardNoSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableForwardNo(m *models.ForwardNoSetter) {
	if !(m.ChatID.IsValue()) {
		val := random_int64(nil)
		m.ChatID = omit.From(val)
	}
	if !(m.ChannelID.IsValue()) {
		val := random_string(nil)
		m.ChannelID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.ForwardNo
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ForwardNoTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.ForwardNo) error {
	var err error

	return err
}

// Create builds a forwardNo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ForwardNoTemplate) Create(ctx context.Context, exec bob.Executor) (*models.ForwardNo, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableForwardNo(opt)

	m, err := models.ForwardNos.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a forwardNo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ForwardNoTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.ForwardNo {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a forwardNo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ForwardNoTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.ForwardNo {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple forwardNos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ForwardNoTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ForwardNoSlice, error) {
	var err error
	m := make(models.ForwardNoSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple forwardNos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ForwardNoTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ForwardNoSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple forwardNos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ForwardNoTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ForwardNoSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// ForwardNo has methods that act as mods for the ForwardNoTemplate
var ForwardNoMods forwardNoMods

type forwardNoMods struct{}

func (m forwardNoMods) RandomizeAllColumns(f *faker.Faker) ForwardNoMod {
	return ForwardNoModSlice{
		ForwardNoMods.RandomID(f),
		ForwardNoMods.RandomChatID(f),
		ForwardNoMods.RandomChannelID(f),
		ForwardNoMods.RandomCreatedAt(f),
		ForwardNoMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m forwardNoMods) ID(val int64) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m forwardNoMods) IDFunc(f func() int64) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m forwardNoMods) UnsetID() ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m forwardNoMods) RandomID(f *faker.Faker) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m forwardNoMods) ChatID(val int64) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.ChatID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m forwardNoMods) ChatIDFunc(f func() int64) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.ChatID = f
	})
}

// Clear any values for the column
func (m forwardNoMods) UnsetChatID() ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.ChatID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m forwardNoMods) RandomChatID(f *faker.Faker) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.ChatID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m forwardNoMods) ChannelID(val string) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.ChannelID = func() string { return val }
	})
}

// Set the Column from the function
func (m forwardNoMods) ChannelIDFunc(f func() string) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.ChannelID = f
	})
}

// Clear any values for the column
func (m forwardNoMods) UnsetChannelID() ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.ChannelID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m forwardNoMods) RandomChannelID(f *faker.Faker) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.ChannelID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m forwardNoMods) CreatedAt(val time.Time) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m forwardNoMods) CreatedAtFunc(f func() time.Time) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m forwardNoMods) UnsetCreatedAt() ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m forwardNoMods) RandomCreatedAt(f *faker.Faker) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m forwardNoMods) UpdatedAt(val time.Time) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m forwardNoMods) UpdatedAtFunc(f func() time.Time) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m forwardNoMods) UnsetUpdatedAt() ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m forwardNoMods) RandomUpdatedAt(f *faker.Faker) ForwardNoMod {
	return ForwardNoModFunc(func(_ context.Context, o *ForwardNoTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m forwardNoMods) WithParentsCascading() ForwardNoMod {
	return ForwardNoModFunc(func(ctx context.Context, o *ForwardNoTemplate) {
		if isDone, _ := forwardNoWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = forwardNoWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
