// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/JasonKhew96/margaretbot/models"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type SubscriptionMod interface {
	Apply(context.Context, *SubscriptionTemplate)
}

type SubscriptionModFunc func(context.Context, *SubscriptionTemplate)

func (f SubscriptionModFunc) Apply(ctx context.Context, n *SubscriptionTemplate) {
	f(ctx, n)
}

type SubscriptionModSlice []SubscriptionMod

func (mods SubscriptionModSlice) Apply(ctx context.Context, n *SubscriptionTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// SubscriptionTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type SubscriptionTemplate struct {
	ID           func() int64
	ChannelID    func() string
	Regex        func() null.Val[string]
	CreatedAt    func() time.Time
	UpdatedAt    func() time.Time
	RegexBan     func() null.Val[string]
	ChannelTitle func() null.Val[string]
	ExpiredAt    func() null.Val[time.Time]
	ThreadID     func() int64

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the SubscriptionTemplate
func (o *SubscriptionTemplate) Apply(ctx context.Context, mods ...SubscriptionMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Subscription
// according to the relationships in the template. Nothing is inserted into the db
func (t SubscriptionTemplate) setModelRels(o *models.Subscription) {}

// BuildSetter returns an *models.SubscriptionSetter
// this does nothing with the relationship templates
func (o SubscriptionTemplate) BuildSetter() *models.SubscriptionSetter {
	m := &models.SubscriptionSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.ChannelID != nil {
		val := o.ChannelID()
		m.ChannelID = omit.From(val)
	}
	if o.Regex != nil {
		val := o.Regex()
		m.Regex = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}
	if o.RegexBan != nil {
		val := o.RegexBan()
		m.RegexBan = omitnull.FromNull(val)
	}
	if o.ChannelTitle != nil {
		val := o.ChannelTitle()
		m.ChannelTitle = omitnull.FromNull(val)
	}
	if o.ExpiredAt != nil {
		val := o.ExpiredAt()
		m.ExpiredAt = omitnull.FromNull(val)
	}
	if o.ThreadID != nil {
		val := o.ThreadID()
		m.ThreadID = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.SubscriptionSetter
// this does nothing with the relationship templates
func (o SubscriptionTemplate) BuildManySetter(number int) []*models.SubscriptionSetter {
	m := make([]*models.SubscriptionSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Subscription
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SubscriptionTemplate.Create
func (o SubscriptionTemplate) Build() *models.Subscription {
	m := &models.Subscription{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.ChannelID != nil {
		m.ChannelID = o.ChannelID()
	}
	if o.Regex != nil {
		m.Regex = o.Regex()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}
	if o.RegexBan != nil {
		m.RegexBan = o.RegexBan()
	}
	if o.ChannelTitle != nil {
		m.ChannelTitle = o.ChannelTitle()
	}
	if o.ExpiredAt != nil {
		m.ExpiredAt = o.ExpiredAt()
	}
	if o.ThreadID != nil {
		m.ThreadID = o.ThreadID()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.SubscriptionSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SubscriptionTemplate.CreateMany
func (o SubscriptionTemplate) BuildMany(number int) models.SubscriptionSlice {
	m := make(models.SubscriptionSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableSubscription(m *models.SubscriptionSetter) {
	if !(m.ChannelID.IsValue()) {
		val := random_string(nil)
		m.ChannelID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Subscription
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *SubscriptionTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Subscription) error {
	var err error

	return err
}

// Create builds a subscription and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *SubscriptionTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Subscription, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableSubscription(opt)

	m, err := models.Subscriptions.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a subscription and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *SubscriptionTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Subscription {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a subscription and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *SubscriptionTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Subscription {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple subscriptions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o SubscriptionTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.SubscriptionSlice, error) {
	var err error
	m := make(models.SubscriptionSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple subscriptions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o SubscriptionTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.SubscriptionSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple subscriptions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o SubscriptionTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.SubscriptionSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Subscription has methods that act as mods for the SubscriptionTemplate
var SubscriptionMods subscriptionMods

type subscriptionMods struct{}

func (m subscriptionMods) RandomizeAllColumns(f *faker.Faker) SubscriptionMod {
	return SubscriptionModSlice{
		SubscriptionMods.RandomID(f),
		SubscriptionMods.RandomChannelID(f),
		SubscriptionMods.RandomRegex(f),
		SubscriptionMods.RandomCreatedAt(f),
		SubscriptionMods.RandomUpdatedAt(f),
		SubscriptionMods.RandomRegexBan(f),
		SubscriptionMods.RandomChannelTitle(f),
		SubscriptionMods.RandomExpiredAt(f),
		SubscriptionMods.RandomThreadID(f),
	}
}

// Set the model columns to this value
func (m subscriptionMods) ID(val int64) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) IDFunc(f func() int64) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetID() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m subscriptionMods) RandomID(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) ChannelID(val string) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ChannelID = func() string { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) ChannelIDFunc(f func() string) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ChannelID = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetChannelID() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ChannelID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m subscriptionMods) RandomChannelID(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ChannelID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) Regex(val null.Val[string]) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.Regex = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) RegexFunc(f func() null.Val[string]) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.Regex = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetRegex() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.Regex = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m subscriptionMods) RandomRegex(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.Regex = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m subscriptionMods) RandomRegexNotNull(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.Regex = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) CreatedAt(val time.Time) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) CreatedAtFunc(f func() time.Time) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetCreatedAt() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m subscriptionMods) RandomCreatedAt(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) UpdatedAt(val time.Time) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) UpdatedAtFunc(f func() time.Time) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetUpdatedAt() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m subscriptionMods) RandomUpdatedAt(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) RegexBan(val null.Val[string]) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.RegexBan = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) RegexBanFunc(f func() null.Val[string]) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.RegexBan = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetRegexBan() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.RegexBan = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m subscriptionMods) RandomRegexBan(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.RegexBan = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m subscriptionMods) RandomRegexBanNotNull(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.RegexBan = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) ChannelTitle(val null.Val[string]) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ChannelTitle = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) ChannelTitleFunc(f func() null.Val[string]) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ChannelTitle = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetChannelTitle() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ChannelTitle = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m subscriptionMods) RandomChannelTitle(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ChannelTitle = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m subscriptionMods) RandomChannelTitleNotNull(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ChannelTitle = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) ExpiredAt(val null.Val[time.Time]) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ExpiredAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) ExpiredAtFunc(f func() null.Val[time.Time]) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ExpiredAt = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetExpiredAt() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ExpiredAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m subscriptionMods) RandomExpiredAt(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ExpiredAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m subscriptionMods) RandomExpiredAtNotNull(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ExpiredAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m subscriptionMods) ThreadID(val int64) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ThreadID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m subscriptionMods) ThreadIDFunc(f func() int64) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ThreadID = f
	})
}

// Clear any values for the column
func (m subscriptionMods) UnsetThreadID() SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ThreadID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m subscriptionMods) RandomThreadID(f *faker.Faker) SubscriptionMod {
	return SubscriptionModFunc(func(_ context.Context, o *SubscriptionTemplate) {
		o.ThreadID = func() int64 {
			return random_int64(f)
		}
	})
}

func (m subscriptionMods) WithParentsCascading() SubscriptionMod {
	return SubscriptionModFunc(func(ctx context.Context, o *SubscriptionTemplate) {
		if isDone, _ := subscriptionWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = subscriptionWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
