// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Caches = Table[
	cacheColumns,
	cacheIndexes,
	cacheForeignKeys,
	cacheUniques,
	cacheChecks,
]{
	Schema: "",
	Name:   "cache",
	Columns: cacheColumns{
		VideoID: column{
			Name:      "video_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsPublished: column{
			Name:      "is_published",
			DBType:    "BOOLEAN",
			Default:   "FALSE",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsScheduled: column{
			Name:      "is_scheduled",
			DBType:    "BOOLEAN",
			Default:   "FALSE",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: cacheIndexes{
		SqliteAutoindexCache1: index{
			Type: "pk",
			Name: "sqlite_autoindex_cache_1",
			Columns: []indexColumn{
				{
					Name:         "video_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_cache",
		Columns: []string{"video_id"},
		Comment: "",
	},

	Comment: "",
}

type cacheColumns struct {
	VideoID     column
	CreatedAt   column
	UpdatedAt   column
	IsPublished column
	IsScheduled column
}

func (c cacheColumns) AsSlice() []column {
	return []column{
		c.VideoID, c.CreatedAt, c.UpdatedAt, c.IsPublished, c.IsScheduled,
	}
}

type cacheIndexes struct {
	SqliteAutoindexCache1 index
}

func (i cacheIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexCache1,
	}
}

type cacheForeignKeys struct{}

func (f cacheForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type cacheUniques struct{}

func (u cacheUniques) AsSlice() []constraint {
	return []constraint{}
}

type cacheChecks struct{}

func (c cacheChecks) AsSlice() []check {
	return []check{}
}
