// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var ForwardNos = Table[
	forwardNoColumns,
	forwardNoIndexes,
	forwardNoForeignKeys,
	forwardNoUniques,
	forwardNoChecks,
]{
	Schema: "",
	Name:   "forward_no",
	Columns: forwardNoColumns{
		ID: column{
			Name:      "id",
			DBType:    "INTEGER",
			Default:   "auto_increment",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ChatID: column{
			Name:      "chat_id",
			DBType:    "INTEGER",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ChannelID: column{
			Name:      "channel_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: forwardNoIndexes{
		PKMainForwardNo: index{
			Type: "pk",
			Name: "pk_main_forward_no",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
		ForwardNoIdx: index{
			Type: "c",
			Name: "forward_no_idx",
			Columns: []indexColumn{
				{
					Name:         "chat_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "channel_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_forward_no",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type forwardNoColumns struct {
	ID        column
	ChatID    column
	ChannelID column
	CreatedAt column
	UpdatedAt column
}

func (c forwardNoColumns) AsSlice() []column {
	return []column{
		c.ID, c.ChatID, c.ChannelID, c.CreatedAt, c.UpdatedAt,
	}
}

type forwardNoIndexes struct {
	PKMainForwardNo index
	ForwardNoIdx    index
}

func (i forwardNoIndexes) AsSlice() []index {
	return []index{
		i.PKMainForwardNo, i.ForwardNoIdx,
	}
}

type forwardNoForeignKeys struct{}

func (f forwardNoForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type forwardNoUniques struct{}

func (u forwardNoUniques) AsSlice() []constraint {
	return []constraint{}
}

type forwardNoChecks struct{}

func (c forwardNoChecks) AsSlice() []check {
	return []check{}
}
