// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Forwards = Table[
	forwardColumns,
	forwardIndexes,
	forwardForeignKeys,
	forwardUniques,
	forwardChecks,
]{
	Schema: "",
	Name:   "forward",
	Columns: forwardColumns{
		ChatID: column{
			Name:      "chat_id",
			DBType:    "INTEGER",
			Default:   "auto_increment",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Regex: column{
			Name:      "regex",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		RegexBan: column{
			Name:      "regex_ban",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: forwardIndexes{
		PKMainForward: index{
			Type: "pk",
			Name: "pk_main_forward",
			Columns: []indexColumn{
				{
					Name:         "chat_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_forward",
		Columns: []string{"chat_id"},
		Comment: "",
	},

	Comment: "",
}

type forwardColumns struct {
	ChatID    column
	Regex     column
	RegexBan  column
	CreatedAt column
	UpdatedAt column
}

func (c forwardColumns) AsSlice() []column {
	return []column{
		c.ChatID, c.Regex, c.RegexBan, c.CreatedAt, c.UpdatedAt,
	}
}

type forwardIndexes struct {
	PKMainForward index
}

func (i forwardIndexes) AsSlice() []index {
	return []index{
		i.PKMainForward,
	}
}

type forwardForeignKeys struct{}

func (f forwardForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type forwardUniques struct{}

func (u forwardUniques) AsSlice() []constraint {
	return []constraint{}
}

type forwardChecks struct{}

func (c forwardChecks) AsSlice() []check {
	return []check{}
}
