// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Subscriptions = Table[
	subscriptionColumns,
	subscriptionIndexes,
	subscriptionForeignKeys,
	subscriptionUniques,
	subscriptionChecks,
]{
	Schema: "",
	Name:   "subscription",
	Columns: subscriptionColumns{
		ID: column{
			Name:      "id",
			DBType:    "INTEGER",
			Default:   "auto_increment",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ChannelID: column{
			Name:      "channel_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ThreadID: column{
			Name:      "thread_id",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Regex: column{
			Name:      "regex",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ExpiredAt: column{
			Name:      "expired_at",
			DBType:    "TIMESTAMP",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "TIMESTAMP",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RegexBan: column{
			Name:      "regex_ban",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ChannelTitle: column{
			Name:      "channel_title",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: subscriptionIndexes{
		PKMainSubscription: index{
			Type: "pk",
			Name: "pk_main_subscription",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
		SubscriptionChannelIDIdx: index{
			Type: "c",
			Name: "subscription_channel_id_idx",
			Columns: []indexColumn{
				{
					Name:         "channel_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "thread_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexSubscription1: index{
			Type: "u",
			Name: "sqlite_autoindex_subscription_1",
			Columns: []indexColumn{
				{
					Name:         "channel_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_subscription",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: subscriptionUniques{
		SqliteAutoindexSubscription1: constraint{
			Name:    "sqlite_autoindex_subscription_1",
			Columns: []string{"channel_id"},
			Comment: "",
		},
	},

	Comment: "",
}

type subscriptionColumns struct {
	ID           column
	ChannelID    column
	ThreadID     column
	Regex        column
	ExpiredAt    column
	CreatedAt    column
	UpdatedAt    column
	RegexBan     column
	ChannelTitle column
}

func (c subscriptionColumns) AsSlice() []column {
	return []column{
		c.ID, c.ChannelID, c.ThreadID, c.Regex, c.ExpiredAt, c.CreatedAt, c.UpdatedAt, c.RegexBan, c.ChannelTitle,
	}
}

type subscriptionIndexes struct {
	PKMainSubscription           index
	SubscriptionChannelIDIdx     index
	SqliteAutoindexSubscription1 index
}

func (i subscriptionIndexes) AsSlice() []index {
	return []index{
		i.PKMainSubscription, i.SubscriptionChannelIDIdx, i.SqliteAutoindexSubscription1,
	}
}

type subscriptionForeignKeys struct{}

func (f subscriptionForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type subscriptionUniques struct {
	SqliteAutoindexSubscription1 constraint
}

func (u subscriptionUniques) AsSlice() []constraint {
	return []constraint{
		u.SqliteAutoindexSubscription1,
	}
}

type subscriptionChecks struct{}

func (c subscriptionChecks) AsSlice() []check {
	return []check{}
}
