// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CacheErrors = &cacheErrors{
	ErrUniquePkMainCache: &UniqueConstraintError{
		schema:  "",
		table:   "cache",
		columns: []string{"video_id"},
		s:       "pk_main_cache",
	},
}

type cacheErrors struct {
	ErrUniquePkMainCache *UniqueConstraintError
}
