// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var ForwardErrors = &forwardErrors{
	ErrUniquePkMainForward: &UniqueConstraintError{
		schema:  "",
		table:   "forward",
		columns: []string{"chat_id"},
		s:       "pk_main_forward",
	},
}

type forwardErrors struct {
	ErrUniquePkMainForward *UniqueConstraintError
}
