// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SubscriptionErrors = &subscriptionErrors{
	ErrUniquePkMainSubscription: &UniqueConstraintError{
		schema:  "",
		table:   "subscription",
		columns: []string{"id"},
		s:       "pk_main_subscription",
	},

	ErrUniqueSqliteAutoindexSubscription1: &UniqueConstraintError{
		schema:  "",
		table:   "subscription",
		columns: []string{"channel_id"},
		s:       "sqlite_autoindex_subscription_1",
	},
}

type subscriptionErrors struct {
	ErrUniquePkMainSubscription *UniqueConstraintError

	ErrUniqueSqliteAutoindexSubscription1 *UniqueConstraintError
}
