// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q sqlite.Filterable]() struct {
	Caches        cacheWhere[Q]
	Forwards      forwardWhere[Q]
	ForwardNos    forwardNoWhere[Q]
	Subscriptions subscriptionWhere[Q]
} {
	return struct {
		Caches        cacheWhere[Q]
		Forwards      forwardWhere[Q]
		ForwardNos    forwardNoWhere[Q]
		Subscriptions subscriptionWhere[Q]
	}{
		Caches:        buildCacheWhere[Q](Caches.Columns),
		Forwards:      buildForwardWhere[Q](Forwards.Columns),
		ForwardNos:    buildForwardNoWhere[Q](ForwardNos.Columns),
		Subscriptions: buildSubscriptionWhere[Q](Subscriptions.Columns),
	}
}
