// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
)

// Cache is an object representing the database table.
type Cache struct {
	VideoID     string    `db:"video_id,pk" `
	CreatedAt   time.Time `db:"created_at" `
	UpdatedAt   time.Time `db:"updated_at" `
	IsPublished bool      `db:"is_published" `
	IsScheduled bool      `db:"is_scheduled" `
}

// CacheSlice is an alias for a slice of pointers to Cache.
// This should almost always be used instead of []*Cache.
type CacheSlice []*Cache

// Caches contains methods to work with the cache table
var Caches = sqlite.NewTablex[*Cache, CacheSlice, *CacheSetter]("", "cache", buildCacheColumns("cache"))

// CachesQuery is a query on the cache table
type CachesQuery = *sqlite.ViewQuery[*Cache, CacheSlice]

func buildCacheColumns(alias string) cacheColumns {
	return cacheColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"video_id", "created_at", "updated_at", "is_published", "is_scheduled",
		).WithParent("cache"),
		tableAlias:  alias,
		VideoID:     sqlite.Quote(alias, "video_id"),
		CreatedAt:   sqlite.Quote(alias, "created_at"),
		UpdatedAt:   sqlite.Quote(alias, "updated_at"),
		IsPublished: sqlite.Quote(alias, "is_published"),
		IsScheduled: sqlite.Quote(alias, "is_scheduled"),
	}
}

type cacheColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	VideoID     sqlite.Expression
	CreatedAt   sqlite.Expression
	UpdatedAt   sqlite.Expression
	IsPublished sqlite.Expression
	IsScheduled sqlite.Expression
}

func (c cacheColumns) Alias() string {
	return c.tableAlias
}

func (cacheColumns) AliasedAs(alias string) cacheColumns {
	return buildCacheColumns(alias)
}

// CacheSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CacheSetter struct {
	VideoID     omit.Val[string]    `db:"video_id,pk" `
	CreatedAt   omit.Val[time.Time] `db:"created_at" `
	UpdatedAt   omit.Val[time.Time] `db:"updated_at" `
	IsPublished omit.Val[bool]      `db:"is_published" `
	IsScheduled omit.Val[bool]      `db:"is_scheduled" `
}

func (s CacheSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.VideoID.IsValue() {
		vals = append(vals, "video_id")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	if s.IsPublished.IsValue() {
		vals = append(vals, "is_published")
	}
	if s.IsScheduled.IsValue() {
		vals = append(vals, "is_scheduled")
	}
	return vals
}

func (s CacheSetter) Overwrite(t *Cache) {
	if s.VideoID.IsValue() {
		t.VideoID = s.VideoID.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
	if s.IsPublished.IsValue() {
		t.IsPublished = s.IsPublished.MustGet()
	}
	if s.IsScheduled.IsValue() {
		t.IsScheduled = s.IsScheduled.MustGet()
	}
}

func (s *CacheSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Caches.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"video_id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 5)
		if s.VideoID.IsValue() {
			vals = append(vals, sqlite.Arg(s.VideoID.MustGet()))
		}

		if s.CreatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedAt.MustGet()))
		}

		if s.UpdatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.UpdatedAt.MustGet()))
		}

		if s.IsPublished.IsValue() {
			vals = append(vals, sqlite.Arg(s.IsPublished.MustGet()))
		}

		if s.IsScheduled.IsValue() {
			vals = append(vals, sqlite.Arg(s.IsScheduled.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s CacheSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s CacheSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.VideoID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "video_id")...),
			sqlite.Arg(s.VideoID),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	if s.IsPublished.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "is_published")...),
			sqlite.Arg(s.IsPublished),
		}})
	}

	if s.IsScheduled.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "is_scheduled")...),
			sqlite.Arg(s.IsScheduled),
		}})
	}

	return exprs
}

// FindCache retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCache(ctx context.Context, exec bob.Executor, VideoIDPK string, cols ...string) (*Cache, error) {
	if len(cols) == 0 {
		return Caches.Query(
			sm.Where(Caches.Columns.VideoID.EQ(sqlite.Arg(VideoIDPK))),
		).One(ctx, exec)
	}

	return Caches.Query(
		sm.Where(Caches.Columns.VideoID.EQ(sqlite.Arg(VideoIDPK))),
		sm.Columns(Caches.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CacheExists checks the presence of a single record by primary key
func CacheExists(ctx context.Context, exec bob.Executor, VideoIDPK string) (bool, error) {
	return Caches.Query(
		sm.Where(Caches.Columns.VideoID.EQ(sqlite.Arg(VideoIDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Cache is retrieved from the database
func (o *Cache) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Caches.AfterSelectHooks.RunHooks(ctx, exec, CacheSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Caches.AfterInsertHooks.RunHooks(ctx, exec, CacheSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Caches.AfterUpdateHooks.RunHooks(ctx, exec, CacheSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Caches.AfterDeleteHooks.RunHooks(ctx, exec, CacheSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Cache
func (o *Cache) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.VideoID)
}

func (o *Cache) pkEQ() dialect.Expression {
	return sqlite.Quote("cache", "video_id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Cache
func (o *Cache) Update(ctx context.Context, exec bob.Executor, s *CacheSetter) error {
	v, err := Caches.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Cache record with an executor
func (o *Cache) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Caches.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Cache using the executor
func (o *Cache) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Caches.Query(
		sm.Where(Caches.Columns.VideoID.EQ(sqlite.Arg(o.VideoID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after CacheSlice is retrieved from the database
func (o CacheSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Caches.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Caches.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Caches.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Caches.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CacheSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("cache", "video_id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CacheSlice) copyMatchingRows(from ...*Cache) {
	for i, old := range o {
		for _, new := range from {
			if new.VideoID != old.VideoID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CacheSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Caches.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Cache:
				o.copyMatchingRows(retrieved)
			case []*Cache:
				o.copyMatchingRows(retrieved...)
			case CacheSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Cache or a slice of Cache
				// then run the AfterUpdateHooks on the slice
				_, err = Caches.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CacheSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Caches.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Cache:
				o.copyMatchingRows(retrieved)
			case []*Cache:
				o.copyMatchingRows(retrieved...)
			case CacheSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Cache or a slice of Cache
				// then run the AfterDeleteHooks on the slice
				_, err = Caches.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CacheSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CacheSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Caches.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o CacheSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Caches.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CacheSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Caches.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type cacheWhere[Q sqlite.Filterable] struct {
	VideoID     sqlite.WhereMod[Q, string]
	CreatedAt   sqlite.WhereMod[Q, time.Time]
	UpdatedAt   sqlite.WhereMod[Q, time.Time]
	IsPublished sqlite.WhereMod[Q, bool]
	IsScheduled sqlite.WhereMod[Q, bool]
}

func (cacheWhere[Q]) AliasedAs(alias string) cacheWhere[Q] {
	return buildCacheWhere[Q](buildCacheColumns(alias))
}

func buildCacheWhere[Q sqlite.Filterable](cols cacheColumns) cacheWhere[Q] {
	return cacheWhere[Q]{
		VideoID:     sqlite.Where[Q, string](cols.VideoID),
		CreatedAt:   sqlite.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   sqlite.Where[Q, time.Time](cols.UpdatedAt),
		IsPublished: sqlite.Where[Q, bool](cols.IsPublished),
		IsScheduled: sqlite.Where[Q, bool](cols.IsScheduled),
	}
}
