// Code generated by BobGen sqlite v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
)

// Forward is an object representing the database table.
type Forward struct {
	ChatID    int64            `db:"chat_id,pk" `
	Regex     null.Val[string] `db:"regex" `
	RegexBan  null.Val[string] `db:"regex_ban" `
	CreatedAt time.Time        `db:"created_at" `
	UpdatedAt time.Time        `db:"updated_at" `
}

// ForwardSlice is an alias for a slice of pointers to Forward.
// This should almost always be used instead of []*Forward.
type ForwardSlice []*Forward

// Forwards contains methods to work with the forward table
var Forwards = sqlite.NewTablex[*Forward, ForwardSlice, *ForwardSetter]("", "forward", buildForwardColumns("forward"))

// ForwardsQuery is a query on the forward table
type ForwardsQuery = *sqlite.ViewQuery[*Forward, ForwardSlice]

func buildForwardColumns(tableName string) forwardColumns {
	columnsExpr := expr.NewColumnsExpr(
		"chat_id", "regex", "regex_ban", "created_at", "updated_at",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return forwardColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ChatID:      sqlite.Quote(tableName, "chat_id"),
		Regex:       sqlite.Quote(tableName, "regex"),
		RegexBan:    sqlite.Quote(tableName, "regex_ban"),
		CreatedAt:   sqlite.Quote(tableName, "created_at"),
		UpdatedAt:   sqlite.Quote(tableName, "updated_at"),
	}
}

type forwardColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ChatID     sqlite.Expression
	Regex      sqlite.Expression
	RegexBan   sqlite.Expression
	CreatedAt  sqlite.Expression
	UpdatedAt  sqlite.Expression
}

func (c forwardColumns) Alias() string {
	return c.tableAlias
}

func (forwardColumns) AliasedAs(tableName string) forwardColumns {
	return buildForwardColumns(tableName)
}

func (c forwardColumns) Unqualified() forwardColumns {
	return buildForwardColumns("")
}

// ForwardSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ForwardSetter struct {
	ChatID    omit.Val[int64]      `db:"chat_id,pk" `
	Regex     omitnull.Val[string] `db:"regex" `
	RegexBan  omitnull.Val[string] `db:"regex_ban" `
	CreatedAt omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt omit.Val[time.Time]  `db:"updated_at" `
}

func (s ForwardSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ChatID.IsValue() {
		vals = append(vals, "chat_id")
	}
	if !s.Regex.IsUnset() {
		vals = append(vals, "regex")
	}
	if !s.RegexBan.IsUnset() {
		vals = append(vals, "regex_ban")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ForwardSetter) Overwrite(t *Forward) {
	if s.ChatID.IsValue() {
		t.ChatID = s.ChatID.MustGet()
	}
	if !s.Regex.IsUnset() {
		t.Regex = s.Regex.MustGetNull()
	}
	if !s.RegexBan.IsUnset() {
		t.RegexBan = s.RegexBan.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *ForwardSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Forwards.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"chat_id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 5)
		if s.ChatID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ChatID.MustGet()))
		}

		if !s.Regex.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Regex.MustGetNull()))
		}

		if !s.RegexBan.IsUnset() {
			vals = append(vals, sqlite.Arg(s.RegexBan.MustGetNull()))
		}

		if s.CreatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedAt.MustGet()))
		}

		if s.UpdatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.UpdatedAt.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ForwardSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ForwardSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ChatID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "chat_id")...),
			sqlite.Arg(s.ChatID),
		}})
	}

	if !s.Regex.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "regex")...),
			sqlite.Arg(s.Regex),
		}})
	}

	if !s.RegexBan.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "regex_ban")...),
			sqlite.Arg(s.RegexBan),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindForward retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindForward(ctx context.Context, exec bob.Executor, ChatIDPK int64, cols ...string) (*Forward, error) {
	if len(cols) == 0 {
		return Forwards.Query(
			sm.Where(Forwards.Columns.ChatID.EQ(sqlite.Arg(ChatIDPK))),
		).One(ctx, exec)
	}

	return Forwards.Query(
		sm.Where(Forwards.Columns.ChatID.EQ(sqlite.Arg(ChatIDPK))),
		sm.Columns(Forwards.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ForwardExists checks the presence of a single record by primary key
func ForwardExists(ctx context.Context, exec bob.Executor, ChatIDPK int64) (bool, error) {
	return Forwards.Query(
		sm.Where(Forwards.Columns.ChatID.EQ(sqlite.Arg(ChatIDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Forward is retrieved from the database
func (o *Forward) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Forwards.AfterSelectHooks.RunHooks(ctx, exec, ForwardSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Forwards.AfterInsertHooks.RunHooks(ctx, exec, ForwardSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Forwards.AfterUpdateHooks.RunHooks(ctx, exec, ForwardSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Forwards.AfterDeleteHooks.RunHooks(ctx, exec, ForwardSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the Forward
func (o *Forward) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ChatID)
}

func (o *Forward) pkEQ() dialect.Expression {
	return sqlite.Quote("forward", "chat_id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Forward
func (o *Forward) Update(ctx context.Context, exec bob.Executor, s *ForwardSetter) error {
	v, err := Forwards.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Forward record with an executor
func (o *Forward) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Forwards.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Forward using the executor
func (o *Forward) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Forwards.Query(
		sm.Where(Forwards.Columns.ChatID.EQ(sqlite.Arg(o.ChatID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after ForwardSlice is retrieved from the database
func (o ForwardSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Forwards.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Forwards.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Forwards.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Forwards.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o ForwardSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("forward", "chat_id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ForwardSlice) copyMatchingRows(from ...*Forward) {
	for i, old := range o {
		for _, new := range from {
			if new.ChatID != old.ChatID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ForwardSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Forwards.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Forward:
				o.copyMatchingRows(retrieved)
			case []*Forward:
				o.copyMatchingRows(retrieved...)
			case ForwardSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Forward or a slice of Forward
				// then run the AfterUpdateHooks on the slice
				_, err = Forwards.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ForwardSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Forwards.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Forward:
				o.copyMatchingRows(retrieved)
			case []*Forward:
				o.copyMatchingRows(retrieved...)
			case ForwardSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Forward or a slice of Forward
				// then run the AfterDeleteHooks on the slice
				_, err = Forwards.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ForwardSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ForwardSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Forwards.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ForwardSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Forwards.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ForwardSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Forwards.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type forwardWhere[Q sqlite.Filterable] struct {
	ChatID    sqlite.WhereMod[Q, int64]
	Regex     sqlite.WhereNullMod[Q, string]
	RegexBan  sqlite.WhereNullMod[Q, string]
	CreatedAt sqlite.WhereMod[Q, time.Time]
	UpdatedAt sqlite.WhereMod[Q, time.Time]
}

func (forwardWhere[Q]) AliasedAs(alias string) forwardWhere[Q] {
	return buildForwardWhere[Q](buildForwardColumns(alias))
}

func buildForwardWhere[Q sqlite.Filterable](cols forwardColumns) forwardWhere[Q] {
	return forwardWhere[Q]{
		ChatID:    sqlite.Where[Q, int64](cols.ChatID),
		Regex:     sqlite.WhereNull[Q, string](cols.Regex),
		RegexBan:  sqlite.WhereNull[Q, string](cols.RegexBan),
		CreatedAt: sqlite.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: sqlite.Where[Q, time.Time](cols.UpdatedAt),
	}
}
