// Code generated by BobGen sqlite v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// ForwardNo is an object representing the database table.
type ForwardNo struct {
	ID        int64     `db:"id,pk" `
	ChatID    int64     `db:"chat_id" `
	ChannelID string    `db:"channel_id" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `
}

// ForwardNoSlice is an alias for a slice of pointers to ForwardNo.
// This should almost always be used instead of []*ForwardNo.
type ForwardNoSlice []*ForwardNo

// ForwardNos contains methods to work with the forward_no table
var ForwardNos = sqlite.NewTablex[*ForwardNo, ForwardNoSlice, *ForwardNoSetter]("", "forward_no", buildForwardNoColumns("forward_no"), forwardNoScanMapper)

// ForwardNosQuery is a query on the forward_no table
type ForwardNosQuery = *sqlite.ViewQuery[*ForwardNo, ForwardNoSlice]

func buildForwardNoColumns(tableName string) forwardNoColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "chat_id", "channel_id", "created_at", "updated_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return forwardNoColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildForwardNoColumn(tableName, "id"),
		ChatID:      buildForwardNoColumn(tableName, "chat_id"),
		ChannelID:   buildForwardNoColumn(tableName, "channel_id"),
		CreatedAt:   buildForwardNoColumn(tableName, "created_at"),
		UpdatedAt:   buildForwardNoColumn(tableName, "updated_at"),
	}
}

type forwardNoColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         forwardNoColumn
	ChatID     forwardNoColumn
	ChannelID  forwardNoColumn
	CreatedAt  forwardNoColumn
	UpdatedAt  forwardNoColumn
}

// Alias returns the current table alias for the columns set.
func (c forwardNoColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (forwardNoColumns) AliasedAs(tableName string) forwardNoColumns {
	return buildForwardNoColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c forwardNoColumns) Unqualified() forwardNoColumns {
	return buildForwardNoColumns("")
}

func buildForwardNoColumn(alias, name string) forwardNoColumn {
	return forwardNoColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type forwardNoColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c forwardNoColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c forwardNoColumn) ShouldOmitParens() bool {
	return true
}

// ForwardNoSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ForwardNoSetter struct {
	ID        omit.Val[int64]     `db:"id,pk" `
	ChatID    omit.Val[int64]     `db:"chat_id" `
	ChannelID omit.Val[string]    `db:"channel_id" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s ForwardNoSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.ChatID.IsValue() {
		vals = append(vals, "chat_id")
	}
	if s.ChannelID.IsValue() {
		vals = append(vals, "channel_id")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ForwardNoSetter) Overwrite(t *ForwardNo) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.ChatID.IsValue() {
		t.ChatID = s.ChatID.MustGet()
	}
	if s.ChannelID.IsValue() {
		t.ChannelID = s.ChannelID.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *ForwardNoSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ForwardNos.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ID.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "chat_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ChatID.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ChatID.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "channel_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ChannelID.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ChannelID.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "created_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CreatedAt.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "updated_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.UpdatedAt.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s ForwardNoSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ForwardNoSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.ChatID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "chat_id")...),
			sqlite.Arg(s.ChatID),
		}})
	}

	if s.ChannelID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "channel_id")...),
			sqlite.Arg(s.ChannelID),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func forwardNoScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*ForwardNo, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *ForwardNo) any
	}
	targets := make([]target, 0, 5)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *ForwardNo) any { return &o.ID }})
		case "chat_id":
			targets = append(targets, target{i, func(o *ForwardNo) any { return &o.ChatID }})
		case "channel_id":
			targets = append(targets, target{i, func(o *ForwardNo) any { return &o.ChannelID }})
		case "created_at":
			targets = append(targets, target{i, func(o *ForwardNo) any { return &o.CreatedAt }})
		case "updated_at":
			targets = append(targets, target{i, func(o *ForwardNo) any { return &o.UpdatedAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(ForwardNo)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*ForwardNo, error) {
			return v.(*ForwardNo), nil
		}
}

// FindForwardNo retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindForwardNo(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*ForwardNo, error) {
	if len(cols) == 0 {
		return ForwardNos.Query(
			sm.Where(ForwardNos.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ForwardNos.Query(
		sm.Where(ForwardNos.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(ForwardNos.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ForwardNoExists checks the presence of a single record by primary key
func ForwardNoExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return ForwardNos.Query(
		sm.Where(ForwardNos.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ForwardNo is retrieved from the database
func (o *ForwardNo) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ForwardNos.AfterSelectHooks.RunHooks(ctx, exec, ForwardNoSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ForwardNos.AfterInsertHooks.RunHooks(ctx, exec, ForwardNoSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ForwardNos.AfterUpdateHooks.RunHooks(ctx, exec, ForwardNoSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ForwardNos.AfterDeleteHooks.RunHooks(ctx, exec, ForwardNoSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the ForwardNo
func (o *ForwardNo) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *ForwardNo) pkEQ() dialect.Expression {
	return sqlite.Quote("forward_no", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ForwardNo
func (o *ForwardNo) Update(ctx context.Context, exec bob.Executor, s *ForwardNoSetter) error {
	v, err := ForwardNos.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single ForwardNo record with an executor
func (o *ForwardNo) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ForwardNos.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ForwardNo using the executor
func (o *ForwardNo) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ForwardNos.Query(
		sm.Where(ForwardNos.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after ForwardNoSlice is retrieved from the database
func (o ForwardNoSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ForwardNos.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ForwardNos.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ForwardNos.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ForwardNos.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o ForwardNoSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("forward_no", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ForwardNoSlice) copyMatchingRows(from ...*ForwardNo) {
	fromByPK := make(map[int64]*ForwardNo, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}

		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ForwardNoSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ForwardNos.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ForwardNo:
				o.copyMatchingRows(retrieved)
			case []*ForwardNo:
				o.copyMatchingRows(retrieved...)
			case ForwardNoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ForwardNo or a slice of ForwardNo
				// then run the AfterUpdateHooks on the slice
				_, err = ForwardNos.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ForwardNoSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ForwardNos.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ForwardNo:
				o.copyMatchingRows(retrieved)
			case []*ForwardNo:
				o.copyMatchingRows(retrieved...)
			case ForwardNoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ForwardNo or a slice of ForwardNo
				// then run the AfterDeleteHooks on the slice
				_, err = ForwardNos.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ForwardNoSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ForwardNoSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ForwardNos.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ForwardNoSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ForwardNos.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ForwardNoSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ForwardNos.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type forwardNoWhere[Q sqlite.Filterable] struct {
	cols      forwardNoColumns
	ID        sqlite.WhereMod[Q, int64]
	ChatID    sqlite.WhereMod[Q, int64]
	ChannelID sqlite.WhereMod[Q, string]
	CreatedAt sqlite.WhereMod[Q, time.Time]
	UpdatedAt sqlite.WhereMod[Q, time.Time]
}

func (forwardNoWhere[Q]) AliasedAs(alias string) forwardNoWhere[Q] {
	return buildForwardNoWhere[Q](buildForwardNoColumns(alias))
}

func buildForwardNoWhere[Q sqlite.Filterable](cols forwardNoColumns) forwardNoWhere[Q] {
	return forwardNoWhere[Q]{
		cols:      cols,
		ID:        sqlite.Where[Q, int64](cols.ID.Expression),
		ChatID:    sqlite.Where[Q, int64](cols.ChatID.Expression),
		ChannelID: sqlite.Where[Q, string](cols.ChannelID.Expression),
		CreatedAt: sqlite.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt: sqlite.Where[Q, time.Time](cols.UpdatedAt.Expression),
	}
}
