// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
)

// Subscription is an object representing the database table.
type Subscription struct {
	ID           int64               `db:"id,pk" `
	ChannelID    string              `db:"channel_id" `
	ThreadID     null.Val[int64]     `db:"thread_id" `
	Regex        null.Val[string]    `db:"regex" `
	CreatedAt    time.Time           `db:"created_at" `
	UpdatedAt    time.Time           `db:"updated_at" `
	RegexBan     null.Val[string]    `db:"regex_ban" `
	ChannelTitle null.Val[string]    `db:"channel_title" `
	ExpiredAt    null.Val[time.Time] `db:"expired_at" `
}

// SubscriptionSlice is an alias for a slice of pointers to Subscription.
// This should almost always be used instead of []*Subscription.
type SubscriptionSlice []*Subscription

// Subscriptions contains methods to work with the subscription table
var Subscriptions = sqlite.NewTablex[*Subscription, SubscriptionSlice, *SubscriptionSetter]("", "subscription", buildSubscriptionColumns("subscription"))

// SubscriptionsQuery is a query on the subscription table
type SubscriptionsQuery = *sqlite.ViewQuery[*Subscription, SubscriptionSlice]

func buildSubscriptionColumns(alias string) subscriptionColumns {
	return subscriptionColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "channel_id", "thread_id", "regex", "created_at", "updated_at", "regex_ban", "channel_title", "expired_at",
		).WithParent("subscription"),
		tableAlias:   alias,
		ID:           sqlite.Quote(alias, "id"),
		ChannelID:    sqlite.Quote(alias, "channel_id"),
		ThreadID:     sqlite.Quote(alias, "thread_id"),
		Regex:        sqlite.Quote(alias, "regex"),
		CreatedAt:    sqlite.Quote(alias, "created_at"),
		UpdatedAt:    sqlite.Quote(alias, "updated_at"),
		RegexBan:     sqlite.Quote(alias, "regex_ban"),
		ChannelTitle: sqlite.Quote(alias, "channel_title"),
		ExpiredAt:    sqlite.Quote(alias, "expired_at"),
	}
}

type subscriptionColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	ID           sqlite.Expression
	ChannelID    sqlite.Expression
	ThreadID     sqlite.Expression
	Regex        sqlite.Expression
	CreatedAt    sqlite.Expression
	UpdatedAt    sqlite.Expression
	RegexBan     sqlite.Expression
	ChannelTitle sqlite.Expression
	ExpiredAt    sqlite.Expression
}

func (c subscriptionColumns) Alias() string {
	return c.tableAlias
}

func (subscriptionColumns) AliasedAs(alias string) subscriptionColumns {
	return buildSubscriptionColumns(alias)
}

// SubscriptionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SubscriptionSetter struct {
	ID           omit.Val[int64]         `db:"id,pk" `
	ChannelID    omit.Val[string]        `db:"channel_id" `
	ThreadID     omitnull.Val[int64]     `db:"thread_id" `
	Regex        omitnull.Val[string]    `db:"regex" `
	CreatedAt    omit.Val[time.Time]     `db:"created_at" `
	UpdatedAt    omit.Val[time.Time]     `db:"updated_at" `
	RegexBan     omitnull.Val[string]    `db:"regex_ban" `
	ChannelTitle omitnull.Val[string]    `db:"channel_title" `
	ExpiredAt    omitnull.Val[time.Time] `db:"expired_at" `
}

func (s SubscriptionSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.ChannelID.IsValue() {
		vals = append(vals, "channel_id")
	}
	if !s.ThreadID.IsUnset() {
		vals = append(vals, "thread_id")
	}
	if !s.Regex.IsUnset() {
		vals = append(vals, "regex")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	if !s.RegexBan.IsUnset() {
		vals = append(vals, "regex_ban")
	}
	if !s.ChannelTitle.IsUnset() {
		vals = append(vals, "channel_title")
	}
	if !s.ExpiredAt.IsUnset() {
		vals = append(vals, "expired_at")
	}
	return vals
}

func (s SubscriptionSetter) Overwrite(t *Subscription) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.ChannelID.IsValue() {
		t.ChannelID = s.ChannelID.MustGet()
	}
	if !s.ThreadID.IsUnset() {
		t.ThreadID = s.ThreadID.MustGetNull()
	}
	if !s.Regex.IsUnset() {
		t.Regex = s.Regex.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
	if !s.RegexBan.IsUnset() {
		t.RegexBan = s.RegexBan.MustGetNull()
	}
	if !s.ChannelTitle.IsUnset() {
		t.ChannelTitle = s.ChannelTitle.MustGetNull()
	}
	if !s.ExpiredAt.IsUnset() {
		t.ExpiredAt = s.ExpiredAt.MustGetNull()
	}
}

func (s *SubscriptionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Subscriptions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 9)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if s.ChannelID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ChannelID.MustGet()))
		}

		if !s.ThreadID.IsUnset() {
			vals = append(vals, sqlite.Arg(s.ThreadID.MustGetNull()))
		}

		if !s.Regex.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Regex.MustGetNull()))
		}

		if s.CreatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedAt.MustGet()))
		}

		if s.UpdatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.UpdatedAt.MustGet()))
		}

		if !s.RegexBan.IsUnset() {
			vals = append(vals, sqlite.Arg(s.RegexBan.MustGetNull()))
		}

		if !s.ChannelTitle.IsUnset() {
			vals = append(vals, sqlite.Arg(s.ChannelTitle.MustGetNull()))
		}

		if !s.ExpiredAt.IsUnset() {
			vals = append(vals, sqlite.Arg(s.ExpiredAt.MustGetNull()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s SubscriptionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s SubscriptionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.ChannelID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "channel_id")...),
			sqlite.Arg(s.ChannelID),
		}})
	}

	if !s.ThreadID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "thread_id")...),
			sqlite.Arg(s.ThreadID),
		}})
	}

	if !s.Regex.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "regex")...),
			sqlite.Arg(s.Regex),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	if !s.RegexBan.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "regex_ban")...),
			sqlite.Arg(s.RegexBan),
		}})
	}

	if !s.ChannelTitle.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "channel_title")...),
			sqlite.Arg(s.ChannelTitle),
		}})
	}

	if !s.ExpiredAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "expired_at")...),
			sqlite.Arg(s.ExpiredAt),
		}})
	}

	return exprs
}

// FindSubscription retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSubscription(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Subscription, error) {
	if len(cols) == 0 {
		return Subscriptions.Query(
			sm.Where(Subscriptions.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Subscriptions.Query(
		sm.Where(Subscriptions.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(Subscriptions.Columns.Only(cols...)),
	).One(ctx, exec)
}

// SubscriptionExists checks the presence of a single record by primary key
func SubscriptionExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Subscriptions.Query(
		sm.Where(Subscriptions.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Subscription is retrieved from the database
func (o *Subscription) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Subscriptions.AfterSelectHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Subscriptions.AfterInsertHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Subscriptions.AfterUpdateHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Subscriptions.AfterDeleteHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Subscription
func (o *Subscription) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *Subscription) pkEQ() dialect.Expression {
	return sqlite.Quote("subscription", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Subscription
func (o *Subscription) Update(ctx context.Context, exec bob.Executor, s *SubscriptionSetter) error {
	v, err := Subscriptions.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Subscription record with an executor
func (o *Subscription) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Subscriptions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Subscription using the executor
func (o *Subscription) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Subscriptions.Query(
		sm.Where(Subscriptions.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after SubscriptionSlice is retrieved from the database
func (o SubscriptionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Subscriptions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Subscriptions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Subscriptions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Subscriptions.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o SubscriptionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("subscription", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SubscriptionSlice) copyMatchingRows(from ...*Subscription) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SubscriptionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Subscriptions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Subscription:
				o.copyMatchingRows(retrieved)
			case []*Subscription:
				o.copyMatchingRows(retrieved...)
			case SubscriptionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Subscription or a slice of Subscription
				// then run the AfterUpdateHooks on the slice
				_, err = Subscriptions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SubscriptionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Subscriptions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Subscription:
				o.copyMatchingRows(retrieved)
			case []*Subscription:
				o.copyMatchingRows(retrieved...)
			case SubscriptionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Subscription or a slice of Subscription
				// then run the AfterDeleteHooks on the slice
				_, err = Subscriptions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o SubscriptionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SubscriptionSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Subscriptions.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o SubscriptionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Subscriptions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SubscriptionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Subscriptions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type subscriptionWhere[Q sqlite.Filterable] struct {
	ID           sqlite.WhereMod[Q, int64]
	ChannelID    sqlite.WhereMod[Q, string]
	ThreadID     sqlite.WhereNullMod[Q, int64]
	Regex        sqlite.WhereNullMod[Q, string]
	CreatedAt    sqlite.WhereMod[Q, time.Time]
	UpdatedAt    sqlite.WhereMod[Q, time.Time]
	RegexBan     sqlite.WhereNullMod[Q, string]
	ChannelTitle sqlite.WhereNullMod[Q, string]
	ExpiredAt    sqlite.WhereNullMod[Q, time.Time]
}

func (subscriptionWhere[Q]) AliasedAs(alias string) subscriptionWhere[Q] {
	return buildSubscriptionWhere[Q](buildSubscriptionColumns(alias))
}

func buildSubscriptionWhere[Q sqlite.Filterable](cols subscriptionColumns) subscriptionWhere[Q] {
	return subscriptionWhere[Q]{
		ID:           sqlite.Where[Q, int64](cols.ID),
		ChannelID:    sqlite.Where[Q, string](cols.ChannelID),
		ThreadID:     sqlite.WhereNull[Q, int64](cols.ThreadID),
		Regex:        sqlite.WhereNull[Q, string](cols.Regex),
		CreatedAt:    sqlite.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:    sqlite.Where[Q, time.Time](cols.UpdatedAt),
		RegexBan:     sqlite.WhereNull[Q, string](cols.RegexBan),
		ChannelTitle: sqlite.WhereNull[Q, string](cols.ChannelTitle),
		ExpiredAt:    sqlite.WhereNull[Q, time.Time](cols.ExpiredAt),
	}
}
