// Code generated by BobGen sqlite v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// Subscription is an object representing the database table.
type Subscription struct {
	ID           int64               `db:"id,pk" `
	ChannelID    string              `db:"channel_id" `
	Regex        null.Val[string]    `db:"regex" `
	RegexBan     null.Val[string]    `db:"regex_ban" `
	CreatedAt    time.Time           `db:"created_at" `
	UpdatedAt    time.Time           `db:"updated_at" `
	ChannelTitle null.Val[string]    `db:"channel_title" `
	ExpiredAt    null.Val[time.Time] `db:"expired_at" `
	ThreadID     int64               `db:"thread_id" `
}

// SubscriptionSlice is an alias for a slice of pointers to Subscription.
// This should almost always be used instead of []*Subscription.
type SubscriptionSlice []*Subscription

// Subscriptions contains methods to work with the subscription table
var Subscriptions = sqlite.NewTablex[*Subscription, SubscriptionSlice, *SubscriptionSetter]("", "subscription", buildSubscriptionColumns("subscription"), subscriptionScanMapper)

// SubscriptionsQuery is a query on the subscription table
type SubscriptionsQuery = *sqlite.ViewQuery[*Subscription, SubscriptionSlice]

func buildSubscriptionColumns(tableName string) subscriptionColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "channel_id", "regex", "regex_ban", "created_at", "updated_at", "channel_title", "expired_at", "thread_id",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return subscriptionColumns{
		ColumnsExpr:  columnsExpr,
		tableAlias:   tableName,
		ID:           buildSubscriptionColumn(tableName, "id"),
		ChannelID:    buildSubscriptionColumn(tableName, "channel_id"),
		Regex:        buildSubscriptionColumn(tableName, "regex"),
		RegexBan:     buildSubscriptionColumn(tableName, "regex_ban"),
		CreatedAt:    buildSubscriptionColumn(tableName, "created_at"),
		UpdatedAt:    buildSubscriptionColumn(tableName, "updated_at"),
		ChannelTitle: buildSubscriptionColumn(tableName, "channel_title"),
		ExpiredAt:    buildSubscriptionColumn(tableName, "expired_at"),
		ThreadID:     buildSubscriptionColumn(tableName, "thread_id"),
	}
}

type subscriptionColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	ID           subscriptionColumn
	ChannelID    subscriptionColumn
	Regex        subscriptionColumn
	RegexBan     subscriptionColumn
	CreatedAt    subscriptionColumn
	UpdatedAt    subscriptionColumn
	ChannelTitle subscriptionColumn
	ExpiredAt    subscriptionColumn
	ThreadID     subscriptionColumn
}

// Alias returns the current table alias for the columns set.
func (c subscriptionColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (subscriptionColumns) AliasedAs(tableName string) subscriptionColumns {
	return buildSubscriptionColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c subscriptionColumns) Unqualified() subscriptionColumns {
	return buildSubscriptionColumns("")
}

func buildSubscriptionColumn(alias, name string) subscriptionColumn {
	return subscriptionColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type subscriptionColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c subscriptionColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c subscriptionColumn) ShouldOmitParens() bool {
	return true
}

// SubscriptionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SubscriptionSetter struct {
	ID           omit.Val[int64]         `db:"id,pk" `
	ChannelID    omit.Val[string]        `db:"channel_id" `
	Regex        omitnull.Val[string]    `db:"regex" `
	RegexBan     omitnull.Val[string]    `db:"regex_ban" `
	CreatedAt    omit.Val[time.Time]     `db:"created_at" `
	UpdatedAt    omit.Val[time.Time]     `db:"updated_at" `
	ChannelTitle omitnull.Val[string]    `db:"channel_title" `
	ExpiredAt    omitnull.Val[time.Time] `db:"expired_at" `
	ThreadID     omit.Val[int64]         `db:"thread_id" `
}

func (s SubscriptionSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.ChannelID.IsValue() {
		vals = append(vals, "channel_id")
	}
	if s.Regex.IsValue() || s.Regex.IsNull() {
		vals = append(vals, "regex")
	}
	if s.RegexBan.IsValue() || s.RegexBan.IsNull() {
		vals = append(vals, "regex_ban")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	if s.ChannelTitle.IsValue() || s.ChannelTitle.IsNull() {
		vals = append(vals, "channel_title")
	}
	if s.ExpiredAt.IsValue() || s.ExpiredAt.IsNull() {
		vals = append(vals, "expired_at")
	}
	if s.ThreadID.IsValue() {
		vals = append(vals, "thread_id")
	}
	return vals
}

func (s SubscriptionSetter) Overwrite(t *Subscription) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.ChannelID.IsValue() {
		t.ChannelID = s.ChannelID.MustGet()
	}
	if s.Regex.IsValue() || s.Regex.IsNull() {
		t.Regex = s.Regex.MustGetNull()
	}
	if s.RegexBan.IsValue() || s.RegexBan.IsNull() {
		t.RegexBan = s.RegexBan.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
	if s.ChannelTitle.IsValue() || s.ChannelTitle.IsNull() {
		t.ChannelTitle = s.ChannelTitle.MustGetNull()
	}
	if s.ExpiredAt.IsValue() || s.ExpiredAt.IsNull() {
		t.ExpiredAt = s.ExpiredAt.MustGetNull()
	}
	if s.ThreadID.IsValue() {
		t.ThreadID = s.ThreadID.MustGet()
	}
}

func (s *SubscriptionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Subscriptions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ID.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "channel_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ChannelID.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ChannelID.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "regex":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Regex.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.Regex.MustGetNull()).WriteSQL(ctx, w, d, start)
			}))
		case "regex_ban":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.RegexBan.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.RegexBan.MustGetNull()).WriteSQL(ctx, w, d, start)
			}))
		case "created_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CreatedAt.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "updated_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.UpdatedAt.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "channel_title":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ChannelTitle.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ChannelTitle.MustGetNull()).WriteSQL(ctx, w, d, start)
			}))
		case "expired_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ExpiredAt.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ExpiredAt.MustGetNull()).WriteSQL(ctx, w, d, start)
			}))
		case "thread_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ThreadID.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ThreadID.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s SubscriptionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s SubscriptionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.ChannelID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "channel_id")...),
			sqlite.Arg(s.ChannelID),
		}})
	}

	if s.Regex.IsValue() || s.Regex.IsNull() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "regex")...),
			sqlite.Arg(s.Regex),
		}})
	}

	if s.RegexBan.IsValue() || s.RegexBan.IsNull() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "regex_ban")...),
			sqlite.Arg(s.RegexBan),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	if s.ChannelTitle.IsValue() || s.ChannelTitle.IsNull() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "channel_title")...),
			sqlite.Arg(s.ChannelTitle),
		}})
	}

	if s.ExpiredAt.IsValue() || s.ExpiredAt.IsNull() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "expired_at")...),
			sqlite.Arg(s.ExpiredAt),
		}})
	}

	if s.ThreadID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "thread_id")...),
			sqlite.Arg(s.ThreadID),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func subscriptionScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Subscription, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *Subscription) any
	}
	targets := make([]target, 0, 9)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *Subscription) any { return &o.ID }})
		case "channel_id":
			targets = append(targets, target{i, func(o *Subscription) any { return &o.ChannelID }})
		case "regex":
			targets = append(targets, target{i, func(o *Subscription) any { return &o.Regex }})
		case "regex_ban":
			targets = append(targets, target{i, func(o *Subscription) any { return &o.RegexBan }})
		case "created_at":
			targets = append(targets, target{i, func(o *Subscription) any { return &o.CreatedAt }})
		case "updated_at":
			targets = append(targets, target{i, func(o *Subscription) any { return &o.UpdatedAt }})
		case "channel_title":
			targets = append(targets, target{i, func(o *Subscription) any { return &o.ChannelTitle }})
		case "expired_at":
			targets = append(targets, target{i, func(o *Subscription) any { return &o.ExpiredAt }})
		case "thread_id":
			targets = append(targets, target{i, func(o *Subscription) any { return &o.ThreadID }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(Subscription)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*Subscription, error) {
			return v.(*Subscription), nil
		}
}

// FindSubscription retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSubscription(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Subscription, error) {
	if len(cols) == 0 {
		return Subscriptions.Query(
			sm.Where(Subscriptions.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Subscriptions.Query(
		sm.Where(Subscriptions.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(Subscriptions.Columns.Only(cols...)),
	).One(ctx, exec)
}

// SubscriptionExists checks the presence of a single record by primary key
func SubscriptionExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Subscriptions.Query(
		sm.Where(Subscriptions.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Subscription is retrieved from the database
func (o *Subscription) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Subscriptions.AfterSelectHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Subscriptions.AfterInsertHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Subscriptions.AfterUpdateHooks.RunHooks(ctx, exec, SubscriptionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Subscriptions.AfterDeleteHooks.RunHooks(ctx, exec, SubscriptionSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the Subscription
func (o *Subscription) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *Subscription) pkEQ() dialect.Expression {
	return sqlite.Quote("subscription", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Subscription
func (o *Subscription) Update(ctx context.Context, exec bob.Executor, s *SubscriptionSetter) error {
	v, err := Subscriptions.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Subscription record with an executor
func (o *Subscription) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Subscriptions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Subscription using the executor
func (o *Subscription) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Subscriptions.Query(
		sm.Where(Subscriptions.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after SubscriptionSlice is retrieved from the database
func (o SubscriptionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Subscriptions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Subscriptions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Subscriptions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Subscriptions.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o SubscriptionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("subscription", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SubscriptionSlice) copyMatchingRows(from ...*Subscription) {
	fromByPK := make(map[int64]*Subscription, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}

		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SubscriptionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Subscriptions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Subscription:
				o.copyMatchingRows(retrieved)
			case []*Subscription:
				o.copyMatchingRows(retrieved...)
			case SubscriptionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Subscription or a slice of Subscription
				// then run the AfterUpdateHooks on the slice
				_, err = Subscriptions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SubscriptionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Subscriptions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Subscription:
				o.copyMatchingRows(retrieved)
			case []*Subscription:
				o.copyMatchingRows(retrieved...)
			case SubscriptionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Subscription or a slice of Subscription
				// then run the AfterDeleteHooks on the slice
				_, err = Subscriptions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o SubscriptionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SubscriptionSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Subscriptions.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o SubscriptionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Subscriptions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SubscriptionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Subscriptions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type subscriptionWhere[Q sqlite.Filterable] struct {
	cols         subscriptionColumns
	ID           sqlite.WhereMod[Q, int64]
	ChannelID    sqlite.WhereMod[Q, string]
	Regex        sqlite.WhereNullMod[Q, string]
	RegexBan     sqlite.WhereNullMod[Q, string]
	CreatedAt    sqlite.WhereMod[Q, time.Time]
	UpdatedAt    sqlite.WhereMod[Q, time.Time]
	ChannelTitle sqlite.WhereNullMod[Q, string]
	ExpiredAt    sqlite.WhereNullMod[Q, time.Time]
	ThreadID     sqlite.WhereMod[Q, int64]
}

func (subscriptionWhere[Q]) AliasedAs(alias string) subscriptionWhere[Q] {
	return buildSubscriptionWhere[Q](buildSubscriptionColumns(alias))
}

func buildSubscriptionWhere[Q sqlite.Filterable](cols subscriptionColumns) subscriptionWhere[Q] {
	return subscriptionWhere[Q]{
		cols:         cols,
		ID:           sqlite.Where[Q, int64](cols.ID.Expression),
		ChannelID:    sqlite.Where[Q, string](cols.ChannelID.Expression),
		Regex:        sqlite.WhereNull[Q, string](cols.Regex.Expression),
		RegexBan:     sqlite.WhereNull[Q, string](cols.RegexBan.Expression),
		CreatedAt:    sqlite.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt:    sqlite.Where[Q, time.Time](cols.UpdatedAt.Expression),
		ChannelTitle: sqlite.WhereNull[Q, string](cols.ChannelTitle.Expression),
		ExpiredAt:    sqlite.WhereNull[Q, time.Time](cols.ExpiredAt.Expression),
		ThreadID:     sqlite.Where[Q, int64](cols.ThreadID.Expression),
	}
}
